export const CREATE_MESSAGE_START = "CREATE_MESSAGE_START";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_FAILED = "CREATE_MESSAGE_FAILED";

export const GET_MESSAGE_START = "GET_MESSAGE_START";
export const GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS";
export const GET_MESSAGE_FAILED = "GET_MESSAGE_FAILED";

export const RESET = "RESET";
