export const CREATE_CHAT_START = "CREATE_CHAT_START";
export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS";
export const CREATE_CHAT_FAILED = "CREATE_CHAT_FAILED";

export const GET_CHAT_START = "GET_CHAT_START";
export const GET_CHAT_SUCCESS = "GET_CHAT_SUCCESS";
export const GET_CHAT_FAILED = "GET_CHAT_FAILED";

export const CREATE_GROUP_START = "CREATE_GROUP_START";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAILED = "CREATE_GROUP_FAILED";

export const RENAME_GROUP_START = "RENAME_GROUP_START";
export const RENAME_GROUP_SUCCESS = "RENAME_GROUP_SUCCESS";
export const RENAME_GROUP_FAILED = "RENAME_GROUP_FAILED";

export const RESET = "RESET";
